### ISSUE TITLE
Rename Service Client to IAMCredentialsServiceClient

### ISSUE THREAD

**Issue by chingor13** [googleapis/java-iamcredentials#326]
We have a one-off hack in the microgenerator to maintain the `IamCredentials` name casing when the defined service in the protos is [`IAMCredentials`](https://github.com/googleapis/java-iamcredentials/blob/0b30e1ea79a22a712329f12571e05790ba35d988/proto-google-cloud-iamcredentials-v1/src/main/proto/google/iam/credentials/v1/iamcredentials.proto#L39)

Before the next semver major release, remove this exception and rename the service.

**Comment by suztomo** [comment]
As of today, it's IAMCredentialsProto https://github.com/googleapis/java-iamcredentials/blob/main/proto-google-cloud-iamcredentials-v1/src/main/java/com/google/cloud/iam/credentials/v1/IAMCredentialsProto.java. It might be inconsistent but very likely we don't change the class name.
